state_reorder <- c("S05",
                   "S06", "S07", "S08",
                   "S10",
                   "S13", "S15",
                   "S11","S12",
                   "S01", "S02",
                   "S09", 
                   "S03", "S04",
                   "S14")
state_anno <- c("Highly Transcribed", 
                "Flanking TSS Downstream", 
                "Flanking TSS",
                "Active Promoter",
                "Genic Super-Enhancer",
                "Distal Enhancer",
                "Poised Enhancer",
                "Distal Super-Enhancer",
                "H3K18ac+ Super-Enhancer",
                "Background Desert",
                "Background Desert",
                "Bivalent/Poised promoter",
                "Polycomb-repressed",
                "Polycomb-repressed",
                "H3K18ac+ Enhancer")



state_reorder_model2 <- c("S03", "S04",
                   "S15", 
                   "S01", "S02",
                   "S10",
                   "S05","S06",
                   "S13", "S14",
                   "S11", "S12",
                   "S09", "S08","S07")
state_anno_model2 <- c("Weakly Polycomb-repressed",
                "Polycomb-repressed",
                "Poised Enhancer",
                "Background Desert",
                "Background Desert",
                "Genic Super-Enhancer",
                "Weakly Transcribed",
                "Highly Transcribed",
                "Genic Enhancer",
                "Distal Enhancer",
                "Promoter Super-Enhancer",
                "Distal Super-Enhancer",
                "Active Promoter",
                "Flanking Promoter/Enhancer", 
                "Flanking Promoter")